modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    #logoBlur=false
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="sodiumdynamiclights"
    mandatory=true
    versionRange="[1.0.0, )"
    ordering="NONE"
    side="CLIENT"
[[dependencies."${mod_id}"]]
    modId="curios"
    mandatory=true
    versionRange="[${curios_version}, )"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="fluffy_fur"
    mandatory=false
    versionRange="[${fluffy_fur_version}, )"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="geckolib"
    mandatory=false
    versionRange="[${geckolib_version}, )"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="modonomicon"
    mandatory=false
    versionRange="[${modonomicon_version}, )"
    ordering="NONE"
    side="BOTH"